- name: jenkins-repo
  shell: sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo

- name: rpm package
  shell: sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key

- name: Installation of jenkins
  yum: 
    name: jenkins
    state: present

- name: Enable service jenkins
  ansible.builtin.service:
    name: jenkins
    enabled: yes
    
- name: Start service jenkins, if not started
  ansible.builtin.service:
    name: jenkins
    state: started


