- name: latest version of java
  shell: sudo amazon-linux-extras install java-openjdk11

- name: Installation of git
  yum: 
    name: git
    state: present

- name: Installaion of docker 
  yum: 
    name: docker
    state: present

- name: Enable service docker
  ansible.builtin.service:
    name: docker
    enabled: yes
    
- name: Start service docker, if not started
  ansible.builtin.service:
    name: docker
    state: started